export const projects = [
  {
    title: "Motion Study",
    image: "/assets/images/img1.jpg",
    year: "2025",
    href: "/all-projects/case-study/motion-study",
  },
  {
    title: "Ease of Use",
    image: "/assets/images/img2.jpg",
    year: "2024",
    href: "/all-projects/case-study/ease-use",
  },
  {
    title: "Nomad Land",
    image: "/assets/images/img3.jpg",
    year: "2023",
    href: "/all-projects/case-study/nomad-land",
  },
  {
    title: "City of Lights",
    image: "/assets/images/img4.jpg",
    year: "2022",
    href: "/all-projects/case-study/city-lights",
  },
  {
    title: "Plane of Existence",
    image: "/assets/images/img5.jpg",
    year: "2021",
    href: "/all-projects/case-study/plan-existence",
  },
  {
    title: "Fragments of Time",
    image: "/assets/images/img6.jpg",
    year: "2024",
    href: "/all-projects/case-study/fragments-time",
  },
  {
    title: "Echoes of Silence",
    image: "/assets/images/img7.jpg",
    year: "2023",
    href: "/all-projects/case-study/echoes-silence",
  },
  {
    title: "Future Tense",
    image: "/assets/images/img8.jpg",
    year: "2025",
    href: "/all-projects/case-study/future-tense",
  },
  {
    title: "Last Horizon",
    image: "/assets/images/img9.jpg",
    year: "2022",
    href: "/all-projects/case-study/last-horizon",
  },
  {
    title: "Neon Pulse",
    image: "/assets/images/img10.jpg",
    year: "2021",
    href: "/all-projects/case-study/neon-pulse",
  },
  {
    title: "Wanderlust",
    image: "/assets/images/img11.jpg",
    year: "2024",
    href: "/all-projects/case-study/wanderlust",
  },
  {
    title: "Dream Archive",
    image: "/assets/images/img12.jpg",
    year: "2023",
    href: "/all-projects/case-study/dream-archive",
  },
  {
    title: "Parallel Lives",
    image: "/assets/images/img13.jpg",
    year: "2025",
    href: "/all-projects/case-study/parallel-lives",
  },
  {
    title: "Digital Mirage",
    image: "/assets/images/img14.jpg",
    year: "2022",
    href: "/all-projects/case-study/digital-mirage",
  },
  {
    title: "Lost Frequencies",
    image: "/assets/images/img15.jpg",
    year: "2023",
    href: "/all-projects/case-study/lost-frequencies",
  },
  {
    title: "Gravity Shift",
    image: "/assets/images/img6.jpg",
    year: "2021",
    href: "/all-projects/case-study/gravity-shift",
  },
  {
    title: "Shadow Realm",
    image: "/assets/images/img7.jpg",
    year: "2022",
    href: "/all-projects/case-study/shadow-realm",
  },
  {
    title: "Monochrome Memories",
    image: "/assets/images/img8.jpg",
    year: "2024",
    href: "/all-projects/case-study/monochrome-memories",
  },
  {
    title: "Celestial Drift",
    image: "/assets/images/img9.jpg",
    year: "2025",
    href: "/all-projects/case-study/celestial-drift",
  },
  {
    title: "Silent Syntax",
    image: "/assets/images/img10.jpg",
    year: "2023",
    href: "/all-projects/case-study/silent-syntax",
  },
  {
    title: "Beyond the Frame",
    image: "/assets/images/img11.jpg",
    year: "2024",
    href: "/all-projects/case-study/beyond-frame",
  },
  {
    title: "Crimson Circuit",
    image: "/assets/images/img12.jpg",
    year: "2022",
    href: "/all-projects/case-study/crimson-circuit",
  },
  {
    title: "Analog Soul",
    image: "/assets/images/img13.jpg",
    year: "2021",
    href: "/all-projects/case-study/analog-soul",
  },
  {
    title: "Timeless Bloom",
    image: "/assets/images/img14.jpg",
    year: "2023",
    href: "/all-projects/case-study/timeless-bloom",
  },
  {
    title: "Reflected Light",
    image: "/assets/images/img15.jpg",
    year: "2022",
    href: "/all-projects/case-study/reflected-light",
  },
];
