export const sliderContent = [
  {
    name: "Strive",
    img1: "/assets/images/imgproject1.avif",
    img2: "/assets/images/imgproject5.avif",
    url: "/case-study/strive",
    link: "www.strive-platform.xyz",
    des: "(An app for buying, selling, and trading sneakers) tailored for the youth. Jorden focuses on a simple experience with a minimalist and youthful design.",
    tag: "©01",
    quantity: 1,
    category: [{ title: "Branding" }, { title: "Art Direction" }],
  },
  {
    name: "Lenas",
    img1: "/assets/images/imgproject2.avif",
    img2: "/assets/images/imgproject1.avif",
    link: "www.lenas.cloud",
    des: "(An app for buying, selling, and trading sneakers) tailored for the youth. Jorden focuses on a simple experience with a minimalist and youthful design.",
    url: "/case-study/lenas",
    tag: "©02",
    quantity: 2,
    category: [{ title: "Mobile App" }, { title: "UX Research" }],
  },
  {
    name: "Gondi UI",
    tag: "©03",
    link: "www.gondiui.xyz",
    des: "(An app for buying, selling, and trading sneakers) tailored for the youth. Jorden focuses on a simple experience with a minimalist and youthful design.",
    img1: "/assets/images/imgproject3.avif",
    img2: "/assets/images/imgproject1.avif",
    url: "/case-study/gondi-ui",
  },
  {
    name: "Blog",
    tag: "©04",
    link: "www.thienducblog.xyz",
    des: "(An app for buying, selling, and trading sneakers) tailored for the youth. Jorden focuses on a simple experience with a minimalist and youthful design.",
    img1: "/assets/images/imgproject4.avif",
    img2: "/assets/images/imgproject2.avif",
    url: "/case-study/blog",
  },
  {
    name: "Vios",
    tag: "©05",
    des: "(An app for buying, selling, and trading sneakers) tailored for the youth. Jorden focuses on a simple experience with a minimalist and youthful design.",
    img1: "/assets/images/imgproject1.avif",
    img2: "/assets/images/imgproject5.avif",
    url: "/case-study/vios",
  },
];

export const siteData = [
  { name: "Doflamingo", position: "CEO of Glam Dusk" },
  { name: "Nico Robin", position: "Head of Research" },
  { name: "Zoro", position: "Creative Director" },
  { name: "Sanji", position: "Chief Marketing Officer" },
  { name: "Nami", position: "Finance Manager" },
  { name: "Law", position: "Operations Lead" },
  { name: "Kid", position: "Tech Advisor" },
  { name: "Boa Hancock", position: "Brand Ambassador" },
  { name: "Ace", position: "Senior Designer" },
  { name: "Shanks", position: "Investor" },
  { name: "Kaido", position: "Partnership Head" },
  { name: "Big Mom", position: "Strategy Lead" },
  { name: "Buggy", position: "PR Manager" },
  { name: "Koby", position: "Junior Analyst" },
  { name: "Smoker", position: "Product Lead" },
];

export const messages = [
  "This partnership has effectively redefined our identity.",
  "Working together boosted creativity and innovation.",
  "The project exceeded expectations in every way.",
  "Collaboration has been seamless and inspiring.",
  "We achieved results faster than anticipated.",
  "A wonderful synergy between both teams.",
  "Truly a groundbreaking experience.",
  "The alignment with core values is impressive.",
  "Innovation and trust were at the heart of this.",
  "Exceeded benchmarks in product quality.",
];
